### ISSUE TITLE
使用 egg-sequelize-extends后原来能用的代码不再能用

### ISSUE THREAD

**Issue by ray-zyh** [zhangmingfeng/egg-sequelize-extends#1]
之前plugin配置用egg-sequelize是正常能用的,配置为此扩展就报错,
报错代码如下:
await _ctx.model.User.findAll({
          where: {
            // user_name: params.user_name //只用此行,不用下面的 $or 就不会报错
            $or: [{ //采用此 $or 就报错
                user_name: params.user_name
              },
              {
                user_phone: params.user_phone
              }
            ]
          }
        });

对应版本如下 
 "egg-bin": "^4.3.5",
    "egg-ci": "^1.8.0",
 "egg": "^2.2.1",
 "egg-sequelize": "^4.3.1",
    "egg-sequelize-extends": "^1.0.5",

**Comment by zhangmingfeng** [comment]
你确认下你配置egg-sequelize的时候版本是什么？egg-sequelize-extends里面依赖的"egg-sequelize": "^4.1.0",理论上不会有问题的，因为findAll是sequelize的api，和egg-sequelize-extends和egg-sequelize都没有关系的，另外，可以将你的错误信息发出来，方便定位

**Comment by zhangmingfeng** [comment]
@ray-zyh 你确认下你配置egg-sequelize的时候版本是什么？egg-sequelize-extends里面依赖的"egg-sequelize": "^4.1.0",理论上不会有问题的，因为findAll是sequelize的api，和egg-sequelize-extends和egg-sequelize都没有关系的，另外，可以将你的错误信息发出来，方便定位

**Comment by zhangmingfeng** [comment]
@ray-zyh 请参考[sequelizejs-findAll](http://docs.sequelizejs.com/manual/tutorial/querying.html)对or关键字的用法，$or是不是已经不给用了？应该使用Symbol？
`Post.findAll({
  where: {
    [Op.or]: [{authorId: 12}, {authorId: 13}]
  }
});`
