### ISSUE TITLE
单独分离出来的sql日志没有按天分隔文件

### ISSUE THREAD

**Issue by johnfanyong** [zhangmingfeng/egg-sequelize-extends#2]
运行环境：
"egg": "^2.2.1",
"egg-cors": "^2.2.0",
"egg-downloader": "^1.0.5",
"egg-logview": "^2.0.0",
"egg-scripts": "^2.5.0",
"egg-sequelize": "^4.3.1",
"egg-sequelize-extends": "^1.0.5",
配置文件如下：
config.default.js:
 `config.logger = {
    level: "DEBUG",
    allowDebugAtProd: true
  };` 
plugin.js:
`exports.sequelize = {
  enable: true,
  logger: {
    level: "ERROR"
  },
  //package: "egg-sequelize"
  package: "egg-sequelize-extends"
};`
现象是sql日志文件不会按天创建新文件，所以自己设置了level=ERROR，但是任然打印INFO日志，日志文件已经打印了1.2G了。

**Comment by zhangmingfeng** [comment]
sql日志的level参数是配置在config文件里的，不是plugin里，请参考readme文件！已经修复文件不自动分割的问题，请更新至最新版本
